//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinemovietickitproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public int ShowtimeID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int SeatsBooked { get; set; }
        public decimal TotalPrice { get; set; }
        public string SeatNumbers { get; set; }
        public string SeatTypes { get; set; }
    
        public virtual Showtime Showtime { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public TimeSpan StartTime { get; internal set; }
    }
}
