//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinemovietickitproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbmovietickitEntities1 : DbContext
    {
        public dbmovietickitEntities1()
            : base("name=dbmovietickitEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<Movy> Movies { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Showtime> Showtimes { get; set; }
        public DbSet<Theatre> Theatres { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
