//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinemovietickitproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public Movy()
        {
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int MovieID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
