//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinemovietickitproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showtime
    {
        public Showtime()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int ShowtimeID { get; set; }
        public int MovieID { get; set; }
        public int TheatreID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Movy Movy { get; set; }
        public virtual Theatre Theatre { get; set; }
    }
}
