//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinemovietickitproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theatre
    {
        public Theatre()
        {
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int TheatreID { get; set; }
        public string TheatreName { get; set; }
        public string Location { get; set; }
        public int TotalSeats { get; set; }
    
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
