//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onlinemovietickitproject.Models
{
    using System;
    using System.Collections.Generic;
    using PagedList;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Bookings = new HashSet<Booking>();
            this.Moviees = new List<Movieapi>();
            this.Moviedata = new List<Movy>();
            this.TheatreData = new List<Theatre>();
            this.showtimesData = new List<Showtime>();
        }

        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }

        public List<Movieapi> Moviees { get; set; }  // Original movie list
        public List<Movy> Moviedata { get; set; }    // Extended movie data
        public IPagedList<Movy> Moviecatagory { get; set; }  // Paged movie category

        public List<Theatre> TheatreData { get; set; }
        public List<Showtime> showtimesData { get; set; }
    }
}
